name: Node.js Test, Build and Notify

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install jest --save-dev
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
        
    - name: Publish Docker
      if: success()
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        # The name of the image you would like to push
        name: momoconsulting/nodeweb
        # The login username for the registry
        username: ${{ secrets.DOCKERHUB_USER }}
        # The login password for the registry
        password: ${{ secrets.DOCKERHUB_PASS }}

  
    - name: GitHub Action for Slack
      if: success()
      env:
       SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      uses: Ilshidur/action-slack@1.6.2
      with:
       args: 'A new version of your Node.js app has been built'
